### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by mparpaillon** [chrisben/imgcache.js#97] opened 2015-01-18 20:08 UTC
Hi,

The imgcache.js library works fine on my laptop but I can't get it to work on my iPad.
I always get a "Not allowed to load local resource" when my img tag tries to get the local cached file...

I'm using Angular so I tried to disable $sceProvider to see what happens but it still fails.
Anyway, since it works on my laptop, I'm pretty sure the problem doesn't comes from Angular.

Thx by advance

**Comment by chrisben** [comment] 2015-01-18 20:38
I believe you're experiencing [this issue](https://github.com/phonegap/phonegap-app-developer/issues/134) caused by the file transfer plugin.
Since phonegap is called cordova and it was split up into plugins it looks like quality went downhill.. 

I hope to get rid of at least this dependency to filetransfer as I've seen somewhere cordova might support xhr .. 

Could you please be my guinea pig to test that by commenting out code near line 380 as below:-

```javascript
    Private.FileTransferWrapper = function (filesystem) {
//        if (Helpers.isCordova()) {
            // PHONEGAP
//            this.fileTransfer = new FileTransfer();
//        }
        this.filesystem = filesystem;	// only useful for CHROME (and maybe cordova...!)
    };
 ```
and let me know if that works!

**Comment by mparpaillon** [comment] 2015-01-18 21:17
This change gives me this
```
ERROR: Download error code: 5
```

**Comment by chrisben** [comment] 2015-01-18 21:27
Well, it looks like it's not happy about this..

About your initial problem, "on your laptop" means via the Chrome browser? or iOS through the emulator?

**Comment by mparpaillon** [comment] 2015-01-18 21:28
No via Chrome (with Ripple)

**Comment by mparpaillon** [comment] 2015-01-18 22:03
I tried with the iOS Emulator but I get the same issue as on my iPad.
"Not allowed to load local resource", and "ERROR: Download error code: 5" when I comment the lines you told me to

**Comment by chrisben** [comment] 2015-01-18 22:20
Ok, never mind for my test with the code commenting, that was a far-fetched solution.

For your problem, I suggest you look into cordova or its file transfer plugin forums/issues. Look for your error message there and see what you can get.

Bonne chance!

**Comment by chrisben** [comment] 2015-02-08 16:17
@mparpaillon  v1.0rc1 includes a fix with paths in iOS, hopefully this should fix your problem. Could you please test this version? Cheers.

**Comment by Maistho** [comment] 2015-04-07 21:18
I've just tested this version on my app, and I also get that very same error. Has anyone found a fix for this yet?

**Comment by Maistho** [comment] 2015-04-07 21:51
So after some digging around I found a fix for it. #115

**Comment by chrisben** [comment] 2015-04-17 14:07
@mparpaillon : please test @Maistho's fix.

**Comment by mparpaillon** [comment] 2015-04-17 14:10
I'm trying this out this WE ! Thanks

**Comment by chrisben** [comment] 2015-04-17 14:14
Cheers.

**Comment by 5amfung** [comment] 2015-08-30 04:34
Should https://github.com/chrisben/imgcache.js/pull/115 be merged here if it fixed the issue?

**Comment by biesbjerg** [comment] 2015-10-28 14:27
#115 also makes it work for me on iOS.

**Comment by chrisben** [comment] 2015-10-31 16:16
Please test the new version in master.

**Closed by chrisben** 2015-10-31 16:16 UTC

**Comment by ted-ks** [comment] 2015-11-07 20:44
Hi I was trying to use the latest version of ImgCache for My Android Device. But the images are not loading and show icons as not found.
A little debugging found that entry.toInternalURL() is returning a Path like - cdvfile://localhost/persistent/imgcacehe/<...>.
But this url is failing to load in the app/webview. Searching for errors in logcat says "Unknown Chromium Error: 0". 

I tried with entry.toURL() and it works fine and images are loading without any issue. 

Is this issue can be related to any configuration in my Code or a bug ?

Cordova vers - 5.2.0
Android SDK - 18 
Using the master of ImgCache

**Comment by Maistho** [comment] 2015-11-07 20:47
@ted-ks what version of Android are you running?

**Comment by chrisben** [comment] 2015-11-07 21:04
Android SDK 18 is Android 4.3.

**Comment by ted-ks** [comment] 2015-11-07 21:17
My Bad.. I had only "<access origin="*"/>" in my config.xml.. I assumed that was enough for cdv protocol also, but was woring  Adding <access origin="cdvfile://*" /> fixed the issue. Images are loading properly now.

**Comment by FromBucketsToRainBarrels** [comment] 2017-02-16 03:41
this error is back on the latest build ???

![image](https://cloud.githubusercontent.com/assets/22966445/23006471/f00a0234-f3cf-11e6-812b-93b47e4f8a38.png)

**Comment by Maistho** [comment] 2017-02-16 04:37
@FromBucketsToRainBarrels see #199 for a fix if you really need to use the cordova browser platform.
