### ISSUE TITLE
IOS 513 issue

### ISSUE THREAD

**Issue by mo3taz-abdallh** [chrisben/imgcache.js#93] opened 2014-12-23 16:27 UTC
Hello 
I got the following error in IOS

FileTransferError {
    body = "Could not create path to save downloaded file: The operation couldn't be completed. (Cocoa error 513.)";
    code = 1;
    "http_status" = 200;
    source = "www.example.com/imagehost.axd/64394.Png";
    target = "file://localhost/var/mobile/Applications/2E8D9FA9-C1E9-493B-A518-5157E7BFAEE7/Documents/imageCache/e33c844c85286e2fc11a0e2495053ec6de17d95b.png";
}
Any one have suggestions, also i have included file permissions in config.xml
Regards

**Comment by chrisben** [comment] 2015-01-07 22:08
Thanks @mo3taz-abdallh . This has now made it into master.

**Comment by boardman** [comment] 2015-01-08 16:03
Hi

I'm still seeing this issue on iOS even when using 0.7.6 (the main imgcache.js file still shows version as 0.7.5 BTW).

I'm testing on device with iOS 8.1.2, using cordova 4.0.0 and 1.3.1 of cordova file plugin.

The only options i'm setting before calling init() are as follows

```
ImgCache.options.debug = true;
ImgCache.options.chromeQuota = 50*1024*1024;
```

I'm seeing output similar to the following when calling `ImgCache.cacheFile()`

```
INFO: LocalFileSystem opened
INFO: Local cache folder opened: /imgcache/
INFO: com.apple.MobileBackup metadata set
INFO: Local cache cleared
INFO: current size: 0
INFO: Local cache folder opened: /imgcache/
INFO: com.apple.MobileBackup metadata set

2015-01-08 15:47:36.651 Discover Tiree[3948:912903] FileTransferError {
    body = "Could not create path to save downloaded file: The operation couldn\U2019t be completed. (Cocoa error 513.)";
    code = 1;
    "http_status" = 200;
    source = "http://isleoftiree.com/core/image-resize/?image-url=https://isle-of-tiree.s3.amazonaws.com/media/uploads/accommodation_images/4balinoe/4balinoe_exterior.jpg&width=50&height=50";
    target = "cdvfile://localhost/root/imgcache/35cc306e157fa2b5c897e5d471f3ee45a2ed14e4";
}

2015-01-08 15:47:36.651 Discover Tiree[3948:912903] File Transfer Error: Could not create path to save downloaded file: The operation couldn’t be completed. (Cocoa error 513.)
```

Thanks

**Comment by mo3taz-abdallh** [comment] 2015-01-09 13:10
@boardman 
I have tested entry.fullPath on real devices of different ios version 6,7,8
and it works fine also you could see the previous link. Did you try over Xcode Emulator.

**Comment by boardman** [comment] 2015-01-09 13:24
@mo3taz-abdallh 

`entry.fullPath` throws the 513 error for me when testing on device with iOS 8.1 and also in iOS 8 emulator.

`entry.fullPath` returns `/imgcache/` for me, is that what you see?

**Comment by SatadruBhattacharjee** [comment] 2015-01-12 10:07
Thanks @boardman , 
```
if (device.platform.toLowerCase() == "ios") {
    return entry.nativeURL;
 }
```
Works fine for me in iOS 8.1 Emulator

**Comment by FrigoEU** [comment] 2015-01-15 11:57
The change propsed by boardman also worked for me, just to let you know.

**Comment by chrisben** [comment] 2015-01-16 12:46
This is a recurring problem, and it's really getting annoying.
I don't know if it's caused by cordova, ios/android versions or the environment but it keeps on changing and I can't keep up and test all platforms for all versions.

To avoid any further problems, here's what I suggest: I will make this part modular: you'll be able to choose what works best for your case, with a sensible default based on the feedback I get from you guys.

This way you'll be able to switch to nativeURL, fullPath or what have you simply through options, without having to hack this library.

What do you guys think?

**Comment by nonec** [comment] 2015-01-16 15:30
@chrisben I like the idea of having the choice with no hacking! :) 
It took me a while to find this issue, because I though by the last commit it was already taken care of. Changed it to nativeURL and it started working.
Thanks for doing this library btw and being so quick with support! :+1:

**Comment by mo3taz-abdallh** [comment] 2015-01-16 18:53
@chrisben  I guess that your idea will resolve Cordova environment issues, so i suggest to have option in imageCache to be set to other use fullPath or nativeUrl as i have tried from my side nativeUrl & it won't work for me.
if (device.platform.toLowerCase() == "ios") {
if(ImgCache.options.iosPath.toLowerCase()=="fullpath")
    return entry.fullPath;
else if (ImgCache.options.iosPath.toLowerCase()=="nativeurl")
   return entry.nativeUrl;
else
// TODO Default setting if user not set iosPath option
 }

& according to suggestions we will set default setting .
Regards

**Comment by chrisben** [comment] 2015-01-18 08:43
Ok I will add those options very soon.
It looks like nativeURL works for most people here, so that could be the new default.

Could you please all state:
- the version of cordova + the cordova file plugin you're using
- the version of your iOS target device/simulator
- what works best for you: nativeURL / fullPath / something else
- if you're using any specific framework with it (some people use appgyver / ionic..)

to see if there's some kind of pattern here. Thanks.

**Comment by FrigoEU** [comment] 2015-01-18 08:52
Phonegap 3.6.3
Phonegap File 1.0
iOS 8
nativeUrl
using "plain" Angular

**Comment by mparpaillon** [comment] 2015-01-18 19:45
Cordova 4.1.2
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transfer"
iOS 8.1.2
nativeUrl
using "plain" Angular too

**Comment by nonec** [comment] 2015-01-19 09:30
Cordova 4.1.2
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File-Transfer"
iOS 8.1.2
nativeUrl
ionic framework

**Comment by boardman** [comment] 2015-01-19 10:10
Cordova 4.0.0
org.apache.cordova.file 1.3.1 "File"
org.apache.cordova.file-transfer 0.4.7 "File Transfer"
iOS 8.1.2
nativeURL
Ionic framework

**Comment by mo3taz-abdallh** [comment] 2015-01-19 10:43
Cordova 2.9.0
iOS 8.1.2, 8.1.1, 6.1.3
fullPath
AngularJs

**Comment by SatadruBhattacharjee** [comment] 2015-01-20 11:18
Cordova 4.0.0
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transfer"
iOS 8.1
nativeURL
Ionic framework

**Comment by mikelaurie** [comment] 2015-01-20 15:50
Cordova 4.2
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transfer"
iOS 8.1.2
Ionic 
Angular
nativeURL works for me, thanks @boardman

**Comment by chrisben** [comment] 2015-01-20 21:36
Looks like we've found the problem: @mo3taz-abdallh you're the only one where fullPath works and you're the only one using a version of cordova <3.x , so I guess something must have changed from that point on in cordova (and not in iOS).

Thank you guys for your input, it's clearer now.
I'll try to work on an update soon. In the meantime  you guys with cordova version 3 or 4 should be safe with imgcache v0.7.5.

As I have the attention of everyone, I'll sneak in a question: what do you guys think of the promises branch of imgcache, is it something that should be expanded and merged into master, would that be useful to you?

I see a lot of Angular and Ionic there..
What's your feedback on the performances of Angular for mobile devices (I mean for lower end phones compared to the iphone6)?

**Comment by jonaskac** [comment] 2015-02-03 14:59
@chrisben thanks a lot for this lib. It's helping a lot in my work.

Took me a while to find this issue though, and I'm implementing it right now, to see if it solves the issue.

About your question about promises, I really like it, and think that it's a much cleaner solution, than using callbacks. so +1 on that :)

**Comment by chrisben** [comment] 2015-02-08 15:52
ImgCache 1.0rc1 is out. It includes a fix (hopefully) for this long standing issue for both pre-3.3 and post-3.3 cordova.
It also includes some goodies like the ability to access private methods (you should then be able to override any of them), and a Promises implementation!

Please give it all a try and report any issue to drive this library towards 1.0!

**Closed by chrisben** 2015-02-08 15:52 UTC
